# Regular expression patterns to uniquely identify their respective heart defect types. These are subject to changes. 
# They are ordered in the same way the "d" dictionary object is.

description_patterns = 
[['chromosome 22 (?:.+)? (?:delet|miss)'],
 ['aorta is (?:too |extremely |very )?narrow'],
 [None],
 [None],
 ['atrium is (?:(?:sub)?divided|partitioned)'],
 ['left coronary artery (?:.+)?(?:connect|aris|from)(?:.+)? pulmonary artery'],
 [None],
 ['coronary arter.+ through (?:.+)? \\(?myocardi'],
 [None],
 ['autosomal recessive (?:.+)?(?:disorder|disease).+(?:sinusitis|infertility|dextrocardia)'],
 ['(?:ductus arteriosus (?:.+)?(?:open|.+close))|(?:communication|connection) between (?:the )?pulmonary artery and (?:the )?aorta'],
 ['(?: pulmonary hypertension| cyanosis| erythrocytosis|,|;| and){6}'],
 ['truncus arteriosus .+(?:divide|separate)d?'],
 ['(?:(?:absence|incomplete|poor|improper) .+ (?:of endocardial cushion|of atrioventricular cushion))|(?:(?:endocardial cushion|atrioventricular cushion) .+ (?:absent|poorly|improperly))'],
 ['(?:foramen ovale|hole in the heart) (?:.+)? (?:open|.+close)'],
 ['(?:association|combination) .+ atrial septal defect .+ mitral (?:valve )?stenosis'],
 ['(?:hole|defect|opening) .+ (?:wall|septum) .+ lower chambers'],
 [None],
 ['(?:left side of the heart|left ventricle) (?:is|has) (?:.+ )?(?:under)?develop'],
 [None],
 ['lenti.+electrocardio.+ocular.+pulmonary.+abnormal.+retard.+deaf'],
 [None],
 ['(?:disorder|disease) .+ affect.+connective tissue'],
 [None],
 ['(?: pulmonary stenosis| ventricular septal defect| right ventricular hypertrophy| overriding aorta|,|;| and){8}'],
 [None],
 ['(?:aorta and (?:the )?pulmonary artery|pulmonary artery and (?:the )?aorta) (?:.+ )?(?:aris|connect).+ right ventricle'],
 ['(?:tricuspid .+ (?:missing|absent|abnormal|not form|fails to develop).+|(?:agenesis|absence) of tricuspid)'],
 ['(?: pulmonary (?:valve )?stenosis| atrial septal defects?| right ventricular hypertrophy|,|;| and){6}'],
 ['(?:duplication|extra|three|3) (?:.+ )?chromosome 13'],
 ['(?:duplication|extra|three|3) (?:.+ )?chromosome 18'],
 [None],
 ['(?:one|single) (?:.+ )?ventricle (?:.+ )?instead .+ two'],
 [None],
 ['(?:extra|abnormal) electrical .+ (?:fast|rapid|abnormal) heart'],
 ['heart .+ outside (?:.+ )?thora'],
 ['(?:muscle weakness|periodic paralysis).+(?:change in heart rhythm|arrhythmia)'],
 ['long qt syndrome .+ (?:hearing loss|deafness)'],
 ['long qt syndrome .+ (?:arrhythm)']]
